% ============================================================
%  make_delete_sql.m
%
%  Standalone. Put it in the folder holding the gathered
%  NC_k####_FINAL.csv files and run it.
%
%  It reads the file names, extracts the case IDs, and writes
%  delete_missing_cases.sql next to itself. That SQL removes every
%  case_runs row whose case_id is NOT among the files present, and
%  marks the survivors completed.
%
%  Paste the result into the Supabase SQL editor. The editor runs
%  as a privileged role, so Row Level Security does not block it --
%  which is why it works when a MATLAB DELETE silently does nothing.
%
%  Re-run this whenever the folder changes; the ID list is rebuilt
%  from scratch every time, so it can never drift from the files.
% ============================================================

clc; clear;

% ============================================================
% CONFIGURATION
% ============================================================
FOLDER   = '';                          % empty = folder of this script
TABLE    = 'public.case_runs1';
OUT_SQL  = 'delete_missing_cases.sql';

CASE_ID_MIN = 0;                        % sweep range, for the
CASE_ID_MAX = 63;                      % "still to run" query

% A CSV shorter than this many lines is treated as missing, so an
% empty or header-only file does not get counted as a finished case.
MIN_CSV_LINES = 2;

COPY_TO_CLIPBOARD = true;               % also put the SQL on the clipboard
% ============================================================

if isempty(FOLDER)
    FOLDER = fileparts(mfilename('fullpath'));
end
assert(isfolder(FOLDER), 'Folder not found: %s', FOLDER);

% ---- collect the case IDs ----------------------------------
files = dir(fullfile(FOLDER, 'NC_k*_FINAL.csv'));
ids = [];
short = {};

for k = 1:numel(files)
    tok = regexp(files(k).name, '^NC_k(\d+)_FINAL\.csv$', 'tokens', 'once');
    if isempty(tok); continue; end
    if countLines(fullfile(FOLDER, files(k).name)) < MIN_CSV_LINES
        short{end+1} = files(k).name; %#ok<SAGROW>
        continue;
    end
    ids(end+1) = str2double(tok{1}); %#ok<SAGROW>
end
ids = unique(ids);

assert(~isempty(ids), ...
    ['No NC_k####_FINAL.csv files in %s.\n' ...
     'Generating the SQL from an empty list would delete EVERY row.'], ...
    FOLDER);

fprintf('Folder      : %s\n', FOLDER);
fprintf('CSV files   : %d\n', numel(files));
fprintf('Case IDs    : %d  (min %d, max %d)\n', numel(ids), min(ids), max(ids));
if ~isempty(short)
    fprintf(2, 'Empty/short CSVs ignored: %d\n', numel(short));
    for k = 1:min(10, numel(short)); fprintf(2, '    %s\n', short{k}); end
end

missing = setdiff(CASE_ID_MIN:CASE_ID_MAX, ids);
fprintf('Not present : %d of %d\n\n', numel(missing), ...
        CASE_ID_MAX - CASE_ID_MIN + 1);

% ---- build the SQL -----------------------------------------
idList = wrapList(ids, 68, '    ');

L = {};
L{end+1} = '-- ============================================================';
L{end+1} = sprintf('--  %s', OUT_SQL);
L{end+1} = sprintf('--  generated by make_delete_sql.m on %s', ...
                   datestr(now, 'yyyy-mm-dd HH:MM'));
L{end+1} = '--';
L{end+1} = sprintf('--  Removes every %s row whose case_id is NOT among', TABLE);
L{end+1} = sprintf('--  the %d gathered NC_k####_FINAL.csv files in', numel(ids));
L{end+1} = sprintf('--  %s', FOLDER);
L{end+1} = '--';
L{end+1} = '--  Run in the Supabase SQL editor, one step at a time.';
L{end+1} = '--  STOP THE WORKERS FIRST: a row created minutes ago may';
L{end+1} = '--  belong to a case running right now, and deleting it';
L{end+1} = '--  would let a second machine start the same case.';
L{end+1} = '-- ============================================================';
L{end+1} = '';
L{end+1} = '-- ---- STEP 1: look before you leap --------------------------';
L{end+1} = 'select case_id, computer_id, status, created_at';
L{end+1} = sprintf('from %s', TABLE);
L{end+1} = 'where case_id not in (';
L{end+1} = idList;
L{end+1} = ')';
L{end+1} = 'order by created_at desc;';
L{end+1} = '';
L{end+1} = '';
L{end+1} = '-- ---- STEP 2: the delete ------------------------------------';
L{end+1} = sprintf('delete from %s', TABLE);
L{end+1} = 'where case_id not in (';
L{end+1} = idList;
L{end+1} = ');';
L{end+1} = '';
L{end+1} = '';
L{end+1} = '-- ---- STEP 3: close out the cases you actually have ---------';
L{end+1} = '-- After step 2 the remaining rows are exactly the cases with';
L{end+1} = '-- a CSV, so marking them completed is accurate and stops any';
L{end+1} = '-- machine redoing them.';
L{end+1} = sprintf('update %s', TABLE);
L{end+1} = 'set status = ''completed'',';
L{end+1} = '    finished_at = now()';
L{end+1} = 'where status <> ''completed'';';
L{end+1} = '';
L{end+1} = '';
L{end+1} = '-- ---- STEP 4: check -----------------------------------------';
L{end+1} = sprintf('select status, count(*) from %s group by status;', TABLE);
L{end+1} = sprintf('-- expect: completed  %d   (one row per case)', numel(ids));
L{end+1} = '';
L{end+1} = '';
L{end+1} = '-- ---- which cases still need running ------------------------';
L{end+1} = 'select g as todo_case_id';
L{end+1} = sprintf('from generate_series(%d, %d) g', CASE_ID_MIN, CASE_ID_MAX);
L{end+1} = sprintf('left join %s c on c.case_id = g', TABLE);
L{end+1} = 'where c.id is null';
L{end+1} = 'order by g;';
L{end+1} = '';
L{end+1} = sprintf('-- currently absent (%d): %s', numel(missing), ...
                   strtrim(wrapList(missing, 60, '--   ')));

sqlText = strjoin(L, newline);

outFile = fullfile(FOLDER, OUT_SQL);
fid = fopen(outFile, 'w');
assert(fid > 0, 'Could not write %s', outFile);
fwrite(fid, sqlText, 'char');
fclose(fid);

fprintf('SQL written : %s\n', outFile);

if COPY_TO_CLIPBOARD
    try
        clipboard('copy', sqlText);
        fprintf('Also copied to the clipboard - paste it into the SQL editor.\n');
    catch
        fprintf('(clipboard unavailable; open the file instead)\n');
    end
end


% ============================================================
% LOCAL FUNCTIONS
% ============================================================
function s = wrapList(v, width, indent)
% Comma-separated integers wrapped to `width` columns, each line
% prefixed with `indent`.
v = v(:).';
if isempty(v); s = [indent '-1']; return; end   % never an empty IN ()
lines = {};
line  = '';
for i = 1:numel(v)
    tok = sprintf('%d', v(i));
    if i < numel(v); tok = [tok ',']; end %#ok<AGROW>
    if isempty(line)
        line = tok;
    elseif numel(line) + 1 + numel(tok) > width
        lines{end+1} = line; %#ok<AGROW>
        line = tok;
    else
        line = [line ' ' tok]; %#ok<AGROW>
    end
end
lines{end+1} = line;
s = strjoin(cellfun(@(x) [indent x], lines, 'UniformOutput', false), newline);
end


function n = countLines(f)
n = 0;
fid = fopen(f, 'r');
if fid < 0; return; end
while ischar(fgetl(fid)); n = n + 1; end
fclose(fid);
end