-- ============================================================
--  delete_missing_cases.sql
--  generated by make_delete_sql.m on 2026-08-17 15:40
--
--  Removes every public.case_runs1 row whose case_id is NOT among
--  the 53 gathered NC_k####_FINAL.csv files in
--  C:\Users\shojaee\Nextcloud\Shoja Saba\DataPANN\Case5_TranslationMode3_6x6_2D_10PercentCircularInclusionContrast_Fonly_F11F22F12_S2_mesh03
--
--  Run in the Supabase SQL editor, one step at a time.
--  STOP THE WORKERS FIRST: a row created minutes ago may
--  belong to a case running right now, and deleting it
--  would let a second machine start the same case.
-- ============================================================

-- ---- STEP 1: look before you leap --------------------------
select case_id, computer_id, status, created_at
from public.case_runs1
where case_id not in (
    3, 8, 14, 28, 43, 50, 54, 55, 60, 63, 65, 66, 68, 70, 71, 74, 85,
    86, 87, 96, 104, 105, 111, 123, 140, 149, 153, 154, 162, 164, 169,
    176, 189, 192, 195, 203, 209, 213, 214, 219, 221, 231, 232, 236,
    240, 241, 242, 245, 246, 264, 265, 268, 271
)
order by created_at desc;


-- ---- STEP 2: the delete ------------------------------------
delete from public.case_runs1
where case_id not in (
    3, 8, 14, 28, 43, 50, 54, 55, 60, 63, 65, 66, 68, 70, 71, 74, 85,
    86, 87, 96, 104, 105, 111, 123, 140, 149, 153, 154, 162, 164, 169,
    176, 189, 192, 195, 203, 209, 213, 214, 219, 221, 231, 232, 236,
    240, 241, 242, 245, 246, 264, 265, 268, 271
);


-- ---- STEP 3: close out the cases you actually have ---------
-- After step 2 the remaining rows are exactly the cases with
-- a CSV, so marking them completed is accurate and stops any
-- machine redoing them.
update public.case_runs1
set status = 'completed',
    finished_at = now()
where status <> 'completed';


-- ---- STEP 4: check -----------------------------------------
select status, count(*) from public.case_runs1 group by status;
-- expect: completed  53   (one row per case)


-- ---- which cases still need running ------------------------
select g as todo_case_id
from generate_series(0, 273) g
left join public.case_runs1 c on c.case_id = g
where c.id is null
order by g;

-- currently absent (221): --   0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19,
--   20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35,
--   36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 51, 52,
--   53, 56, 57, 58, 59, 61, 62, 64, 67, 69, 72, 73, 75, 76, 77,
--   78, 79, 80, 81, 82, 83, 84, 88, 89, 90, 91, 92, 93, 94, 95,
--   97, 98, 99, 100, 101, 102, 103, 106, 107, 108, 109, 110,
--   112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124,
--   125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
--   137, 138, 139, 141, 142, 143, 144, 145, 146, 147, 148, 150,
--   151, 152, 155, 156, 157, 158, 159, 160, 161, 163, 165, 166,
--   167, 168, 170, 171, 172, 173, 174, 175, 177, 178, 179, 180,
--   181, 182, 183, 184, 185, 186, 187, 188, 190, 191, 193, 194,
--   196, 197, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208,
--   210, 211, 212, 215, 216, 217, 218, 220, 222, 223, 224, 225,
--   226, 227, 228, 229, 230, 233, 234, 235, 237, 238, 239, 243,
--   244, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
--   258, 259, 260, 261, 262, 263, 266, 267, 269, 270, 272, 273