-- ============================================================
--  delete_missing_cases.sql
--  generated by make_delete_sql.m on 2026-08-25 22:09
--
--  Removes every public.case_runs1 row whose case_id is NOT among
--  the 105 gathered NC_k####_FINAL.csv files in
--  D:\esmaeili\nextcloud\Shoja Saba\DataPANN\Case8_TranslationMode3_6x6_2D_20PercentCircularInclusionContrast_FandG_mesh03
--
--  Run in the Supabase SQL editor, one step at a time.
--  STOP THE WORKERS FIRST: a row created minutes ago may
--  belong to a case running right now, and deleting it
--  would let a second machine start the same case.
-- ============================================================

-- ---- STEP 1: look before you leap --------------------------
select case_id, computer_id, status, created_at
from public.case_runs1
where case_id not in (
    1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22,
    23, 24, 25, 27, 30, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43, 44, 45,
    46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 80, 81, 83, 84,
    85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102,
    103, 104, 105, 106, 108, 110, 111, 112, 113, 115, 116, 117, 118,
    119, 121, 123, 124, 125, 127
)
order by created_at desc;


-- ---- STEP 2: the delete ------------------------------------
delete from public.case_runs1
where case_id not in (
    1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22,
    23, 24, 25, 27, 30, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43, 44, 45,
    46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 80, 81, 83, 84,
    85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102,
    103, 104, 105, 106, 108, 110, 111, 112, 113, 115, 116, 117, 118,
    119, 121, 123, 124, 125, 127
);


-- ---- STEP 3: close out the cases you actually have ---------
-- After step 2 the remaining rows are exactly the cases with
-- a CSV, so marking them completed is accurate and stops any
-- machine redoing them.
update public.case_runs1
set status = 'completed',
    finished_at = now()
where status <> 'completed';


-- ---- STEP 4: check -----------------------------------------
select status, count(*) from public.case_runs1 group by status;
-- expect: completed  105   (one row per case)


-- ---- which cases still need running ------------------------
select g as todo_case_id
from generate_series(0, 127) g
left join public.case_runs1 c on c.case_id = g
where c.id is null
order by g;

-- currently absent (23): --   0, 9, 10, 13, 26, 28, 29, 31, 35, 36, 49, 77, 78, 79, 82,
--   91, 98, 107, 109, 114, 120, 122, 126