-- ============================================================
--  delete_missing_cases.sql
--  generated by make_delete_sql.m on 2026-08-26 11:41
--
--  Removes every public.case_runs1 row whose case_id is NOT among
--  the 127 gathered NC_k####_FINAL.csv files in
--  D:\esmaeili\nextcloud\Shoja Saba\DataPANN\Case7_TranslationMode3_6x6_2D_20PercentCircularInclusionContrast_Fonly_mesh03
--
--  Run in the Supabase SQL editor, one step at a time.
--  STOP THE WORKERS FIRST: a row created minutes ago may
--  belong to a case running right now, and deleting it
--  would let a second machine start the same case.
-- ============================================================

-- ---- STEP 1: look before you leap --------------------------
select case_id, computer_id, status, created_at
from public.case_runs1
where case_id not in (
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
    36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53,
    54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
    71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
    88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
    117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127
)
order by created_at desc;


-- ---- STEP 2: the delete ------------------------------------
delete from public.case_runs1
where case_id not in (
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
    36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53,
    54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
    71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
    88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
    117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127
);


-- ---- STEP 3: close out the cases you actually have ---------
-- After step 2 the remaining rows are exactly the cases with
-- a CSV, so marking them completed is accurate and stops any
-- machine redoing them.
update public.case_runs1
set status = 'completed',
    finished_at = now()
where status <> 'completed';


-- ---- STEP 4: check -----------------------------------------
select status, count(*) from public.case_runs1 group by status;
-- expect: completed  127   (one row per case)


-- ---- which cases still need running ------------------------
select g as todo_case_id
from generate_series(0, 127) g
left join public.case_runs1 c on c.case_id = g
where c.id is null
order by g;

-- currently absent (1): --   52