-- ============================================================
--  delete_missing_cases.sql
--  generated by make_delete_sql.m on 2026-08-17 15:30
--
--  Removes every public.case_runs row whose case_id is NOT among
--  the 205 gathered NC_k####_FINAL.csv files in
--  C:\Users\shojaee\Nextcloud\Shoja Saba\DataPANN\Case4_TranslationMode3_6x6_2D_1PercentCircularInclusionContrast_Fonly_F11F22F12_S2_mesh03
--
--  Run in the Supabase SQL editor, one step at a time.
--  STOP THE WORKERS FIRST: a row created minutes ago may
--  belong to a case running right now, and deleting it
--  would let a second machine start the same case.
-- ============================================================

-- ---- STEP 1: look before you leap --------------------------
select case_id, computer_id, status, created_at
from public.case_runs
where case_id not in (
    1, 2, 3, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 55, 57, 58, 59,
    60, 61, 62, 64, 65, 69, 71, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85,
    86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 117, 118,
    119, 120, 122, 123, 125, 126, 132, 133, 135, 136, 137, 138, 139,
    140, 141, 143, 144, 145, 147, 148, 149, 151, 153, 154, 155, 156,
    158, 159, 160, 161, 162, 165, 168, 172, 173, 174, 176, 177, 178,
    179, 180, 182, 184, 185, 186, 192, 193, 194, 195, 196, 197, 199,
    200, 201, 202, 203, 204, 206, 208, 210, 212, 213, 214, 215, 216,
    217, 221, 223, 224, 225, 226, 227, 228, 230, 232, 233, 234, 235,
    237, 238, 240, 241, 242, 244, 245, 246, 248, 250, 251, 252, 253,
    254, 255, 256, 257, 258, 260, 262, 263, 264, 265, 266, 267, 269,
    271, 272
)
order by created_at desc;


-- ---- STEP 2: the delete ------------------------------------
delete from public.case_runs
where case_id not in (
    1, 2, 3, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 55, 57, 58, 59,
    60, 61, 62, 64, 65, 69, 71, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85,
    86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 100, 101, 102, 103,
    104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 117, 118,
    119, 120, 122, 123, 125, 126, 132, 133, 135, 136, 137, 138, 139,
    140, 141, 143, 144, 145, 147, 148, 149, 151, 153, 154, 155, 156,
    158, 159, 160, 161, 162, 165, 168, 172, 173, 174, 176, 177, 178,
    179, 180, 182, 184, 185, 186, 192, 193, 194, 195, 196, 197, 199,
    200, 201, 202, 203, 204, 206, 208, 210, 212, 213, 214, 215, 216,
    217, 221, 223, 224, 225, 226, 227, 228, 230, 232, 233, 234, 235,
    237, 238, 240, 241, 242, 244, 245, 246, 248, 250, 251, 252, 253,
    254, 255, 256, 257, 258, 260, 262, 263, 264, 265, 266, 267, 269,
    271, 272
);


-- ---- STEP 3: close out the cases you actually have ---------
-- After step 2 the remaining rows are exactly the cases with
-- a CSV, so marking them completed is accurate and stops any
-- machine redoing them.
update public.case_runs
set status = 'completed',
    finished_at = now()
where status <> 'completed';


-- ---- STEP 4: check -----------------------------------------
select status, count(*) from public.case_runs group by status;
-- expect: completed  205   (one row per case)


-- ---- which cases still need running ------------------------
select g as todo_case_id
from generate_series(0, 273) g
left join public.case_runs c on c.case_id = g
where c.id is null
order by g;

-- currently absent (69): --   0, 4, 6, 26, 51, 54, 56, 63, 66, 67, 68, 70, 72, 73, 74, 83,
--   89, 99, 114, 116, 121, 124, 127, 128, 129, 130, 131, 134,
--   142, 146, 150, 152, 157, 163, 164, 166, 167, 169, 170, 171,
--   175, 181, 183, 187, 188, 189, 190, 191, 198, 205, 207, 209,
--   211, 218, 219, 220, 222, 229, 231, 236, 239, 243, 247, 249,
--   259, 261, 268, 270, 273